### ISSUE TITLE
Some Question About Dataset 

### ISSUE THREAD

**Issue by PnZheng** [jamycheung/360BEV#3]
Dear Authors:
  When I downloaded the 360-FV dataset, I had found it didn't include label file and it had 42 numbers in .png.  Besides, The dataset includes "self.df = pd.read_csv("eigen13_mapping_from_mpcat40.csv")", it is hard to find the .csv for me. Would you mind sending it to me？ 

Bests.

**Comment by YangJagon** [comment]
Why do the provided 360FOV Matterport labels not correspond one to the other on each chart, is there any conversion relationship?

**Comment by brucetend** [comment]
Hello,


> 

It depends on the starting angle when you stitch the Cube-map

**Comment by brucetend** [comment]
> Dear Authors: When I downloaded the 360-FV dataset, I had found it didn't include label file and it had 42 numbers in .png. Besides, The dataset includes "self.df = pd.read_csv("eigen13_mapping_from_mpcat40.csv")", it is hard to find the .csv for me. Would you mind sending it to me？
> 
> Bests.

Thanks for your question,
the table of this mapping relationship has been uploaded.
Best Regards
