### ISSUE TITLE
How to test？

### ISSUE THREAD

**Issue by yejy53** [jamycheung/360BEV#5]
Your work is very good, but I don't know how to organize the data you provide in Google Drive into a suitable format and test it

**Comment by yejy53** [comment]
Hello, could you tell me how to reformat the extended data that I've downloaded from Google Drive so that it meets the requirements for testing?

**Comment by brucetend** [comment]
Hello! Thanks for your question.
Could you please describe which task you are testing, front-view panoramic segmentation or 360BEV top-view segmentation?  And may I ask which dataset, Matterport3D or Stanford2D3D?

best regards,
