### ISSUE TITLE
Query Regarding Pre-trained mit_b2.pth Checkpoint

### ISSUE THREAD

**Issue by yejy53** [jamycheung/360BEV#6]
I noticed that the project makes use of a checkpoint file named mit_b2.pth. Could you please provide some information about its origin? Specifically:

Where was this checkpoint file downloaded from?
Is it a pre-trained model that does not require further training to be used?
Thank you for your time and effort on this project. Looking forward to your response.

**Comment by brucetend** [comment]
This is actually the pre-trained weight of SegFormer. 
https://github.com/NVlabs/SegFormer
