### ISSUE TITLE
Clarification on the Calculation of masks_inliers and m in BEV360_segnext_s2d3d.py

### ISSUE THREAD

**Issue by yejy53** [jamycheung/360BEV#7]
Hello,

Firstly, I'd like to thank you for sharing this interesting codebase. I have been reviewing the BEV360_segnext_s2d3d.py script and have a couple of questions I hope you could clarify for me:

Could you please explain how the masks_inliers variable is derived in the code? I'd like to understand the logic behind it.

Regarding the variable m, it seems to be derived in a rather unusual way. The threshold_index_m is set as the maximum value of proj_index. As a result, the boolean mask m will mark all elements in proj_index that are smaller than this maximum value as True. The only exception, where m would be False, is when an element in proj_index equals threshold_index_m. Could you please elaborate on the reasoning behind this approach?

I appreciate your time and assistance in advance. Looking forward to your response.

Best regards

![Snipaste_2023-09-08_14-44-32](https://github.com/jamycheung/360BEV/assets/83576010/13db8c99-160d-415f-a4a9-e70364d4cd33)

**Comment by brucetend** [comment]
https://github.com/ rusty1s/pytorch_scatter

**Comment by brucetend** [comment]
Thank you for your question. 
In order to facilitate comparison with previous work, the 360FV task uses 512*1024. The task of 360BEV is indeed to use 1024*2048 resolution images as input. Then 256*512 is because after the image passes through the Segformer encoder, the size of the feature map is 1/4 of the original size.

**Comment by yejy53** [comment]
bev_pos should be the position encoding of bev, not corresponding to the feature map, right? It should have nothing to do with the size of the feature map, right?
