### ISSUE TITLE
360FV-Matterport

### ISSUE THREAD

**Issue by farlit** [jamycheung/360BEV#8]
Dear authors,
      Hello, I greatly admire your impactful and innovative work: 360BEV：Panoramic Semantic Mapping for Indoor Bird’s-Eye View
      When I read your excellent work, I saw:
       "The original Matterport3D [5] was collected via narrow-FoV cameras. As shown in Fig. 3, we convert the 18 narrow-view images and annotations into the 360° format by using rotation-translation matrices."
      Could you please provide the process code of acquiring Matterport3D panoramic segmentation image?
      Thanks！

**Comment by brucetend** [comment]
Dear farlit!
Thank you for your questions.
Regarding your first question, I actually used the tool called matterport_utils. Please check this link https://github.com/atlantis-ar/matterport_utils/tree/master/preparepano, which can be used to convert the 18 narrow-view images into a panoramic image.

**Comment by brucetend** [comment]
> I also find that there aren't depth and rgb images in 360FV-Matterport, can you provide them? Thank you.

I think I'll add these images soon.

**Comment by farlit** [comment]
Dear&nbsp;brucetend，
&nbsp; &nbsp; &nbsp; Thank you for your patience.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月10日(星期二) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jamycheung/360BEV] 360FV-Matterport (Issue #8)





 
Dear farlit!
 Thank you for your questions.
 Regarding your first question, I actually used the tool called matterport_utils. Please check this link https://github.com/atlantis-ar/matterport_utils/tree/master/preparepano, which can be used to convert the 18 narrow-view images into a panoramic image.

**Comment by farlit** [comment]
Dear brucetend,
      I've tried many ways and asked my friends to help me, but I still can't download this dataset: 360FV-Matterport.
      I think the reason is that the dataset uploaded to the cloud disk is too large, 50G. Uploads in three steps may solve this problem.
      RGB, depth, semantic should be uploaded separately.
      Thanks!
